### PR TITLE
View: Creates a summary of expenses (weekly & monthly)

### PR DESCRIPTION
**Pull request by gigerbytes**
It only sums the negative values in the 'amounts' table
I thought it would be helpful to have a summary of expenses in the view. Attached a screenshot.

screen shot 2016-05-03 at 19 42 47

P.S. sorry about the commit messages being vague :(

### CODE REVIEW

**Comment by arecker** [comment]
Oh nice.  Thanks for the pull request.  I'll look at this a little later when I have time.

**Comment by gigerbytes** [comment]
cool thanks! any feedback is welcome

**Comment by insajd** [comment]
I actually like the addition. Based on this I added weekly/monthly rate summary for myself (now I got BALANCE, EXPENSES, RATE tabs). It probably would be best presented as graph, but I can't do graphs :smile:

**Comment by arecker** [comment]
Thanks for making `total_expense` as a QuerySet method.  Definitely one of the best design patterns in Django and I'm always happy to see more.

**Comment by gigerbytes** [comment]
Yay thanks!

**Pull request merged**
