### PR TITLE
Fix transaction edit

### PR DESCRIPTION
**Pull request by rainforest1155**
Using your suggested change in #69 I was able to fix the transaction edit. There's now no more error in the console and the change gets applied.
Though, I tested this on a few transactions and rates.

### CODE REVIEW

**Comment by arecker** [comment]
1. Some unit tests are breaking - they are probably not expecting a trailing slash
2. Could you push it to a new branch?  There is a junk merge commit in there because you are pulling from your master before pushing to it.  I'd like to see only one commit in the PR

**Comment by rainforest1155** [comment]
I'm not sure how to do that. From what I understand, I can't directly modify your master repository, which is why I forked that to my own account and modified it from there.
Do you mean that I could directly clone yours, modify it and push it to a new branch on my account? 

When cloning a different repository, how do you preserve the database? Do I just copy the /temp/db.slite3 database file and then copy that back into the new clone? Or is there anything else I need to save?

**Comment by arecker** [comment]
> I'm not sure how to do that.
1. Fork the repo
2. Clone your fork
3. Create a branch for your change: `git checkout -b rename-image`
4. Rename the image
   5.Commit the change
5. Push the new branch to your fork: `git push origin rename-image:rename-image`

The pull request should only show _one_ commit.  You're correct - I have to merge it into my master.

> When cloning a different repository, how do you preserve the database?

`db.sqlite3` is just a testing database.  That's not part of version control.

**Comment by arecker** [comment]
I'm going to close this one.  It's the right idea, just fix the git stuff (and the failing unit test)

**Pull request closed without merging**
