### PR TITLE
fix editing transactions (tracked down by arecker)

### PR DESCRIPTION
**Pull request by rainforest1155**
Finally, there it i again to address #73. Lets see how the build testing works out this time.

### CODE REVIEW

**Comment by rainforest1155** [comment]
Did this change test properly on your timezone branch? It works fine on my end and looking at the console logs without it, the trailing slash is what is needed for the API call to work. I just can't tell if it's added in the correct place.

**Comment by arecker** [comment]
This is the right change, but you also need to update the unit test.

```
Expected '/mock/api/path/beers/:id/' to be '/mock/api/path/beers/:id'
```

**Comment by arecker** [comment]
Take a look at [this](https://github.com/arecker/bennedetto/blob/master/jasmine/services/test_resource.js#L33) assertion.  Adding a trailing slash to the expected value would be appropriate.

**Comment by rainforest1155** [comment]
Thanks, I did not know that I could also modify the unit test. I did that now and it seems to check out.

**Pull request merged**
